spring.application.name=api
# ==========================================
# BANCO DE DADOS H2 -
# ==========================================

# Banco H2 em arquivo
spring.datasource.url=jdbc:h2:file:./data/dbsebrea
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# CONSOLE DO H2
# ==========================================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# SERVIDOR
# ==========================================

server.port=8080
spring.h2.console.settings.web-allow-others=true